### ISSUE TITLE
i can not this library import my project

### ISSUE THREAD

**Issue by enrique15241524** [ahessling/RFM69-STM32#2]
Hi my friend;
Thank you for this library.
i use Keil 5 and STM32F030
but i can not import this library..
can you help me?
Regards....

**Comment by ahessling** [comment]
Hi @enrique15241524,

I have written this library for a low power project of mine, so I included support for a STM32L1 device originally as an example. You can find in commit 421a5c760d4ca736ee5f318db306a5fe73e6eafa a SPI class for STM32F0 devices which I backported to this repository from another project. Please note that I did not test this class in combination with this library, so there might be communication issues. Also, this library has a focus on the RFM69 part and tries not to support all STM32 families, variants and libraries. The latter part should be done by the user/developer because he knows his hardware best.

As to importing the library... Sorry, I cannot help you there. I willingly did not include any project files or Makefiles because there are so many IDEs, toolchains and configurations out there and I cannot support them. Try to provide the functions I referenced in the "Usage" part in the README and use the SPI class for STM32F0 devices.

Kind regards,
André
